- name: preference of variables
  hosts: local
  connection: local
  vars: 
   course: devops
   learner: dhanush

  vars_files:
  - file_variables.yaml

  vars_prompt:
   - name: course
     prompt: enter the course

   - name: learner
     prompt: enter the learner
  
  tasks:
  - name: print the variables
    vars:
     course: ansible
     ansible.builtin.debug:
      msg: the course is {{ course }} and the learner is {{ learner }}

  - name: print the variables
    ansible.builtin.debug:
     msg: the course is {{ course }} and the learner is {{ learner }}
     