- name: Install the nginx based on condition
  hosts: web
  tasks:
  - name: install the nginx if redhat
    ansible.builtin.dnf:
     name: nginx
     state: installed
    when: ansible_os_family = "RedHat"

  - name: install the nignx if ubuntu
    ansible.builtin.apt:
     name: nginx
     state: installed
    when: ansible_os_family = "ubuntu"

    
