- name: accessing the file level variables
  hosts: local
  connection: local
  vars:
   - file_variables.yaml #accesing the variable from this file
  tasks:
  - name : accessing the values from file_variables.yaml
    ansible.builtin.debug:
     msg: the course is {{ course }} and the duration is {{ duration }} and the learner is {{ learner }}  