- name: install the packages
  hosts: local
  connection: local
  tasks:
  - name: handling undefined varaibles
    ansible.builtin.debug:
     msg: hello {{ person | default('dhanush')}} how are you?