- name: install the packages
  hosts: local
  connection: local
  become: yes
  vars_prompt:
    - name: IP
      prompt: Enter the IP address
      private: false
  tasks:
  - name: install the python libs
    ansible.builtin.pip:
     name: netaddr

  - name: handling undefined varaibles
    ansible.builtin.debug:
     msg: hello {{ person | default('dhanush')}} how are you?     #giving default value using piping

  - name: convert string to list
    vars:
     persons: "dhanush,suresh,siva"
    ansible.builtin.debug:
     msg: the persons are {{ persons | split(',')}}


  - name: convert dict to list
    vars:
     course:
       name: "ansible"
       duartion: 120
       trainer: "siva"
    ansible.builtin.debug:
     msg: the persons are {{ course | dict2items }}

  - name: convert to lower case
    vars:
     name: "DHANUSH"
    ansible.builtin.debug:
      msg: the persons are {{ name | lower }}

  - name: convert to upper case
    vars:
     name: "dhanush"
    ansible.builtin.debug:
     msg: the persons are {{ name | upper }}

  - name: find max and min
    vars:
      numbers: [1,34,56,98,314324]
    ansible.builtin.debug:
      msg: "min is {{ numbers | min }} max is {{ numbers | max }}"
    
  - name: check whether IP is valid or not
    ansible.builtin.debug:
     msg: "{{ IP | ansible.builtin.ipaddr }}"