- name: accesing the variables from inventory file
  hosts: local
  connection: local
  tasks:
  - name: accessing the variables from inventory
    ansible.builtin.debug:
     msg: the course is {{ course }} and the duration is {{ duration }} and the learner is {{ learner }}






#[local:vars]
#course=devops
#duration=150hrs
#learner=dhanush
