- name: looping the group
  hosts: local
  connection: local

  tasks:
  - name: looping the values
    loop:
    - apple
    - orange
    - banana
    ansible.builtin.debug:
     msg: the fruit is {{ item }}