- name: install and start nginx
  hosts: web
  become: yes
  tasks:
  - name: install the nginx
    ansible.builtin.package:
     name: nginx
     state: installed
  - name: start the nginx service
    ansible.builtin.service:
     name: nginx
     state: started

# ansible all -i inventory.ini -e anisble_user=ec2-user -e ansible_password=DevOps321 -b -m dnf -a "name=nginx state=installed"