- name: install and start nginx
  hosts: web
  become: yes
  tasks:
  - name: install the nginx
    ansible.builtin.package:
     name: installing nginx
     state: installed
  - name: start the nginx service
    ansible.builtin.service:
     name: starting the nginx
     state: started

