- name: accessing the task level variables
  hosts: local
  connection: local
  vars:
   course: "devops with aws"
   duration: 120
   learner: dhanush
  tasks:
  - name: accessing task level variables
    vars:
      course: ansible #task level variable which is confined to this task only
    ansible.builtin.debug:
     msg: the course is "{{ course }}" and the duration is "{{ duration }}" and the learner is "{{ learner }}"
    


  - name: accessing the variables
    ansible.builtin.debug:
     msg: the course is "{{ course }}" and the duration is "{{ duration }}" and the learner is "{{ learner }}"
