- name: accessing the task level variables
  hosts: local
  collection: local
  vars:
   course: "devops with aws"
   duration: 120
   learner: dhanush
  tasks:
  - name: accesing task level variables
    ansible.builtin.debug:
     msg: the course is "{{ course }}" and the duration is "{{ duration }}" and the learner is "{{ learner }}"
     course: ansible #task level variable
  - name: accesing the variables
    ansible.builtin.debug:
    msg: the course is "{{ course }}" and the duration is "{{ duration }}" and the learner is "{{ learner }}"
