- name: accessing the task level variables
  hosts: local
  connection: local
  vars:
   course: "devops with aws" #global variables play level variables
   duration: 120
   learner: dhanush
  tasks:
  - name: accessing task level variables
    vars:
      course: ansible #task level variable which is confined to this task only
    ansible.builtin.debug:
     msg: the course is {{ course }} and the duration is {{ duration }} and the learner is {{ learner }}
    


  - name: accessing the the task level variables
    vars: 
     course: terraform
     duration: 15hrs
     learner: suresh
    ansible.builtin.debug:
     msg: the course is {{ course }} and the duration is {{ duration }} and the learner is {{ learner }}

  - name: override by global variables
    ansible.builtin.debug:
     msg: the course is {{ course }} and the duration is {{ duration }} and the learner is {{ learner }}

