- name: accessing the variables by prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: course
    prompt: Enter the course name

  - name: duration
    prompt: Enter the duration

  - name: learner
    prompt: Enter the learner name
  tasks:
  - name: the information below
    ansible.builtin.debug:
     msg: the course is {{ course }} and the duration is {{ duration }} and the learner is {{ learner }}